language: rust
cache: cargo

rust:
  - 1.35.0
  - stable
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features
  - cargo test --verbose
  - cargo test --verbose --no-default-features

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta