language: rust
cache: cargo

rust:
  - 1.36.0
  - beta
  - nightly

script:
  - cargo build --verbose
  - cargo build --verbose --no-default-features
  - cargo test --verbose
  - cargo test --verbose --no-default-features

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
