[package]
name = "reclaim"
version = "0.1.0"
authors = ["oliver <oliver.giersch@googlemail.com>"]
edition = "2018"

[features]
default = ["global_alloc"]
global_alloc = []

[dependencies]
cfg-if = "0.1.6"
memoffset = "0.2.1"
