[package]
name = "reclaim"
version = "0.1.0"
authors = ["Oliver Giersch"]
license = "MIT/Apache-2.0"
readme = "README.md"
edition = "2018"

[features]
default = ["with_std"]
# For use in std environments, must be disabled for use in no_std crates
with_std = []

[dependencies]
memoffset = "0.2.1"
typenum = "1.10.0"
